language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t arnabc169/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arnabc169/react-test npm test
  # - docker run arnabc/react-test npm run test -- --coverage

after_success:
  - docker build -t arnabc169/multi-client ./client
  - docker build -t arnabc169/multi-nginx ./nginx
  - docker build -t arnabc169/multi-server ./server
  - docker build -t arnabc169/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- pasword-stdin

  # Take those images and push them to docker hub
  - docker push arnabc169/multi-client
  - docker push arnabc169/multi-nginx
  - docker push arnabc169/multi-server
  - docker push arnabc169/multi-worker

# deploy:
#   provider: elasticbeanstalk
#  region: "ap-south-1"
#  app: "docker-devops-trial-1"
#  env: "DockerDevopsTrial1-env"
#  bucket_name: "elasticbeanstalk-ap-south-1-647813168080"
#  bucket_path: "docker-devops-trial-1"

#  on:
#    branch: master

#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
